@Client NUM_CLIENTE, @User NUM_USUARIO, @Impersonated IMPERSONIFICADO, @Profile NUM_PERFIL, @DESCRIPCION VARCHAR(500), @ESTADO VARCHAR(10), @DIFERENCIA_HORARIA VARCHAR(10), @PERMITE_AGREGAR VARCHAR(10), @INTENTOS_DISCADOR VARCHAR(20), @AUTOCERRARCONTACTOS VARCHAR(10), @INTENTOS_TOTALES VARCHAR(20), @AUTOCERRARCONTACTOS_TOTALES VARCHAR(10), @INTENTOS_DISCADOR_CONTACTO_DIA VARCHAR(20), @INTENTOS_DISCADOR_CONTACTO_MES VARCHAR(20), @CRM_ORDEN_DISCADO VARCHAR(500), @TELEFONOS_A_DISCAR VARCHAR(50)
AS

IF EXISTS (SELECT * FROM DB WHERE DESCRIPCION = @DESCRIPCION)
BEGIN
	SELECT 'ERROR' AS ESTADO, 'Ya existe una base con esa descripcion: ' + @DESCRIPCION AS MENSAJE
	RETURN
END

DECLARE @_DIFERENCIA_HORARIA SMALLINT
DECLARE @_INTENTOS_DISCADOR INT
DECLARE @_INTENTOS_TOTALES INT
DECLARE @_INTENTOS_DISCADOR_CONTACTO_DIA INT
DECLARE @_INTENTOS_DISCADOR_CONTACTO_MES INT

SELECT
	@_DIFERENCIA_HORARIA = CONVERT(SMALLINT, @DIFERENCIA_HORARIA),
	@_INTENTOS_DISCADOR = CONVERT(INT, @INTENTOS_DISCADOR),
	@_INTENTOS_TOTALES = CONVERT(INT, @INTENTOS_TOTALES),
	@_INTENTOS_DISCADOR_CONTACTO_DIA = CONVERT(INT, @INTENTOS_DISCADOR_CONTACTO_DIA),
	@_INTENTOS_DISCADOR_CONTACTO_MES = CONVERT(INT, @INTENTOS_DISCADOR_CONTACTO_MES)

DECLARE @Resultado TABLE (IDDATABASE INT)
INSERT INTO @Resultado
EXEC DB_INSERT
	@DESCRIPCION = @DESCRIPCION,
	@ESTADO = @ESTADO,
	@DIFERENCIA_HORARIA = @_DIFERENCIA_HORARIA,
	@CARACTERISTICA = ' ',
	@PERMITE_AGREGAR = @PERMITE_AGREGAR,
	@USUARIO = NULL,
	@INTENTOS_DISCADOR = @_INTENTOS_DISCADOR,
	@AUTOCERRARCONTACTOS = @AUTOCERRARCONTACTOS,
	@CRM_ORDEN_DISCADO = @CRM_ORDEN_DISCADO,
	@INTENTOS_TOTALES = @_INTENTOS_TOTALES,
	@AUTOCERRARCONTACTOS_TOTALES = @AUTOCERRARCONTACTOS_TOTALES,
	@TELEFONOS_A_DISCAR = @TELEFONOS_A_DISCAR,
	@INTENTOS_DISCADOR_CONTACTO_DIA = @_INTENTOS_DISCADOR_CONTACTO_DIA,
	@INTENTOS_DISCADOR_CONTACTO_MES = @_INTENTOS_DISCADOR_CONTACTO_MES

IF @@ERROR <> 0
BEGIN
	SELECT 'ERROR' AS ESTADO, 'Fallo al crear la base' AS MENSAJE
	RETURN
END

DECLARE @NuevoID INT
SELECT @NuevoID = IDDATABASE FROM @Resultado

SELECT 'OK' AS ESTADO, 'Base creada: ' + CONVERT(varchar(10), @NuevoID) AS MENSAJE
