@Client NUM_CLIENTE, @User NUM_USUARIO, @Impersonated IMPERSONIFICADO, @Profile NUM_PERFIL, @IDDATABASE VARCHAR(20), @DESCRIPCION VARCHAR(500), @ESTADO VARCHAR(10), @DIFERENCIA_HORARIA VARCHAR(10), @PERMITE_AGREGAR VARCHAR(10), @INTENTOS_DISCADOR VARCHAR(20), @AUTOCERRARCONTACTOS VARCHAR(10), @INTENTOS_TOTALES VARCHAR(20), @AUTOCERRARCONTACTOS_TOTALES VARCHAR(10), @INTENTOS_DISCADOR_CONTACTO_DIA VARCHAR(20), @INTENTOS_DISCADOR_CONTACTO_MES VARCHAR(20), @CRM_ORDEN_DISCADO VARCHAR(500), @TELEFONOS_A_DISCAR VARCHAR(50)
AS

DECLARE @_IDDATABASE INT
SELECT @_IDDATABASE = CONVERT(INT, @IDDATABASE)

IF NOT EXISTS (SELECT * FROM DB WHERE IDDATABASE = @_IDDATABASE)
BEGIN
	SELECT 'ERROR' AS ESTADO, 'No existe la base IDDATABASE=' + @IDDATABASE AS MENSAJE
	RETURN
END

DECLARE @_DIFERENCIA_HORARIA SMALLINT
DECLARE @_INTENTOS_DISCADOR INT
DECLARE @_INTENTOS_TOTALES INT
DECLARE @_INTENTOS_DISCADOR_CONTACTO_DIA INT
DECLARE @_INTENTOS_DISCADOR_CONTACTO_MES INT

SELECT
	@_DIFERENCIA_HORARIA = CONVERT(SMALLINT, @DIFERENCIA_HORARIA),
	@_INTENTOS_DISCADOR = CONVERT(INT, @INTENTOS_DISCADOR),
	@_INTENTOS_TOTALES = CONVERT(INT, @INTENTOS_TOTALES),
	@_INTENTOS_DISCADOR_CONTACTO_DIA = CONVERT(INT, @INTENTOS_DISCADOR_CONTACTO_DIA),
	@_INTENTOS_DISCADOR_CONTACTO_MES = CONVERT(INT, @INTENTOS_DISCADOR_CONTACTO_MES)

EXEC DB_UPDATE
	@IDDATABASE = @_IDDATABASE,
	@DESCRIPCION = @DESCRIPCION,
	@ESTADO = @ESTADO,
	@DIFERENCIA_HORARIA = @_DIFERENCIA_HORARIA,
	@CARACTERISTICA = ' ',
	@PERMITE_AGREGAR = @PERMITE_AGREGAR,
	@INTENTOS_DISCADOR = @_INTENTOS_DISCADOR,
	@AUTOCERRARCONTACTOS = @AUTOCERRARCONTACTOS,
	@CRM_ORDEN_DISCADO = @CRM_ORDEN_DISCADO,
	@INTENTOS_TOTALES = @_INTENTOS_TOTALES,
	@AUTOCERRARCONTACTOS_TOTALES = @AUTOCERRARCONTACTOS_TOTALES,
	@TELEFONOS_A_DISCAR = @TELEFONOS_A_DISCAR,
	@INTENTOS_DISCADOR_CONTACTO_DIA = @_INTENTOS_DISCADOR_CONTACTO_DIA,
	@INTENTOS_DISCADOR_CONTACTO_MES = @_INTENTOS_DISCADOR_CONTACTO_MES

IF @@ERROR <> 0
BEGIN
	SELECT 'ERROR' AS ESTADO, 'Fallo al actualizar la base' AS MENSAJE
	RETURN
END

SELECT 'OK' AS ESTADO, 'Base ' + @IDDATABASE + ' actualizada' AS MENSAJE
